on:
  push:
    branches:
      - main

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: 1

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout

      - uses: actions/setup-dotnet@v4
        name: Install dotnet
        with:
          dotnet-version: 8

      - name: Tools
        run: |
          dotnet tool install -g dotnet-reportgenerator-globaltool
          dotnet tool install -g LiquidTestReports.Cli
          dotnet tool install -g dotnet-stryker

      - working-directory: ./src/Checkout.Tests
        name: Test
        run: dotnet test --consoleLoggerParameters:ErrorsOnly --logger "trx;LogFileName=TestResults.trx" --collect:"XPlat Code Coverage" /p:SkipAutoProps=true /p:ExcludeByAttribute=CompilerGenerated

      - name: Test Reports
        working-directory: ./src/Checkout.Tests
        if: ${{ always() }}
        run: |
          liquid --inputs "File=TestResults/testResults.trx;Format=Trx" --output-file TestResults/tests.md
          cat ./TestResults/tests.md >> $GITHUB_STEP_SUMMARY
          cat ./TestResults/tests.md >> $GITHUB_WORKSPACE/PRSUMMARY.md

      - name: Coverage Reports
        id: coverage-reports
        working-directory: ./src/Checkout.Tests
        run: |
          reportgenerator "-reports:./TestResults/*/*.xml" "-targetdir:./TestResults/" "-reporttypes:MarkdownSummaryGithub"
          cat ./TestResults/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
          cat ./TestResults/SummaryGithub.md >> $GITHUB_WORKSPACE/PRSUMMARY.md
          
      - name: Mutation Testing
        id: mutation-testing
        working-directory: ./src/Checkout.Tests
        run: |
          dotnet stryker
